output "asg_name" {
  value       = aws_autoscaling_group.autoscaling_group.name
  description = "This is the name for the autoscaling group generated by the module"
}

output "cluster_size" {
  value       = aws_autoscaling_group.autoscaling_group.desired_capacity
  description = "This is the desired size of the consul cluster in the autoscaling group"
}

output "launch_config_name" {
  value       = aws_launch_configuration.consul_launch_config.name
  description = "This is the name of the launch_configuration used to bootstrap the cluster instances"
}

output "cluster_tag_key" {
  value       = var.cluster_tag_key
  description = "This is the tag key used to allow the consul servers to autojoin"
}

output "cluster_tag_value" {
  value       = var.cluster_tag_value
  description = "This is the tag value used to allow the consul servers to autojoin"
}
output "aws_iam_instance_profile"  {
  value = aws_iam_instance_profile.consul_agent.name
}